apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-app-cert
  namespace: echo
spec:
  secretName: echo-app-tls
  issuerRef:
    name: echo-app-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - echo.app